2013-q1-completed-tasks:
  defaults:
    datetime: 'single'
2013-q1-outstanding-tasks:
  defaults:
    datetime: 'single'
2013-q1-tasks-to-discuss:
  defaults:
    datetime: 'single'
2013-q2-completed-tasks:
  defaults:
    datetime: 'single'
2013-q2-outstanding-tasks:
  defaults:
    datetime: 'single'
2013-q2-tasks-to-discuss:
  defaults:
    datetime: 'single'
2013-q3-completed-tasks:
  defaults:
    datetime: 'single'
2013-q3-outstanding-tasks:
  defaults:
    datetime: 'single'
2013-q3-tasks-to-discuss:
  defaults:
    datetime: 'single'
2013-q4-completed-tasks:
  defaults:
    datetime: 'single'
2013-q4-outstanding-tasks:
  defaults:
    datetime: 'single'
2013-q4-tasks-to-discuss:
  defaults:
    datetime: 'single'
2014-q1-completed-tasks:
  defaults:
    datetime: 'single'
2014-q1-outstanding-tasks:
  defaults:
    datetime: 'single'
2014-q1-tasks-to-discuss:
  defaults:
    datetime: 'single'
2014-q2-completed-tasks:
  defaults:
    datetime: 'single'
2014-q2-outstanding-tasks:
  defaults:
    datetime: 'single'
2014-q2-tasks-to-discuss:
  defaults:
    datetime: 'single'
2014-q3-completed-tasks:
  defaults:
    datetime: 'single'
2014-q3-outstanding-tasks:
  defaults:
    datetime: 'single'
2014-q3-tasks-to-discuss:
  defaults:
    datetime: 'single'
2014-q4-completed-tasks:
  defaults:
    datetime: 'single'
2014-q4-outstanding-tasks:
  defaults:
    datetime: 'single'
2014-q4-tasks-to-discuss:
  defaults:
    datetime: 'single'
2015-q1-completed-tasks:
  defaults:
    datetime: 'single'
2015-q1-outstanding-tasks:
  defaults:
    datetime: 'single'
2015-q1-tasks-to-discuss:
  defaults:
    datetime: 'single'
2015-q2-completed-tasks:
  defaults:
    datetime: 'single'
2015-q2-outstanding-tasks:
  defaults:
    datetime: 'single'
2015-q2-tasks-to-discuss:
  defaults:
    datetime: 'single'
2015-q3-completed-tasks:
  defaults:
    datetime: 'single'
2015-q3-outstanding-tasks:
  defaults:
    datetime: 'single'
2015-q3-tasks-to-discuss:
  defaults:
    datetime: 'single'
2015-q4-completed-tasks:
  defaults:
    datetime: 'single'
2015-q4-outstanding-tasks:
  defaults:
    datetime: 'single'
2015-q4-tasks-to-discuss:
  defaults:
    datetime: 'single'
application-errors:
average-opportunity-age:
cash-reserves:
certificated-datasets:
cumulative-bookings:
cumulative-income:
cumulative-network-size:
cumulative-people-trained:
cumulative-reach:
cumulative-value-unlocked:
current-year-active-reach:
current-year-bookings:
current-year-bookings-by-sector:
current-year-burn:
current-year-commercial-bookings:
current-year-ebitda:
current-year-events-hosted:
current-year-flagship-stories:
current-year-grant-funding:
current-year-headcount:
current-year-income:
current-year-income-by-sector:
current-year-income-by-type:
current-year-kpi-performance:
current-year-network-size:
current-year-non-commercial-bookings:
current-year-passive-reach:
current-year-people-trained:
current-year-pr-pieces:
current-year-press-geographical-spread:
current-year-press-sector-spread:
current-year-press-sentiment:
current-year-press-spokespeople:
current-year-press-totals:
current-year-reach:
current-year-total-costs:
  defaults:
    type: 'target'
    datetime: 'single'
current-year-trainers-trained:
current-year-value-unlocked:
diversity-gender:
gemnasium-dependencies:
github-forks:
github-open-issue-count:
github-open-pull-requests:
github-outgoing-pull-requests:
github-repository-count:
github-total-pull-requests:
github-watchers:
irc-theodi-users:
membership-count:
membership-coverage:
membership-renewals:
old-opportunity-count:
quarterly-progress:
total-pipeline:
weighted-pipeline:
